# redis
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: redis
  name: redis
spec: 
  clusterIP: None
  ports:
  - name: redis-service
    port: 6379
    targetPort: 6379
  selector: 
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: redis

# db
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: db
  name: db
spec: 
  clusterIP: None
  ports: 
  - name: db
    port: 5432
    targetPort: 5432
  selector: 
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:9.4
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


# eventservice
---
apiVersion: v1
kind: Service
metadata:
  name: eventservice
  labels:
    apps: eventservice
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 80
      name: event-service
  selector:
    app: eventservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventservice
  labels:
    app: eventservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventservice
  template:
    metadata:
      labels:
        app: eventservice
    spec:
      containers:
      - name: eventservice
        image: timp/eventservice
        ports:
        - containerPort: 80
          name: eventservice

# queueworker
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: queueworker
  name: queueworker
spec: 
  clusterIP: None
  selector: 
    app: queueworker
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: queueworker
  name: queueworker
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: queueworker
  template: 
    metadata: 
      labels: 
        app: queueworker
    spec: 
      containers: 
      - image: timp/queueworker
        name: queueworker
